name: py3_11_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.11
  - pip
  - pip:
    - ipykernel
    - azureml-rag[faiss]>=0.1.11
    - promptflow[azure]
    - promptflow-tools
    - promptflow-vectordb
    - azure-ai-ml
    - azure-cli
    - azureml-core
    - azureml-mlflow==1.53.0
    - azure-ai-contentsafety
    - keyring>=4.1.1
    - keyrings.alt
    - pytest
    - flask>=2.2.3
    - pymongo

    # Pinned dependencies
    - azureml-inference-server-http


